### ISSUE TITLE
Can you add JAP 9.2.0-20J support package downgrade

### ISSUE THREAD

**Issue by MxCen** [Plailect/PlaiSysUpdater#1]
link  ：http://pan.baidu.com/s/1geftWmZ
pass：dzi3

JPN     9.2.0-20J complete package downgrade
Can not check

**Comment by Plailect** [comment]
Upload a picture of where it fails

**Comment by MxCen** [comment]
![error](https://cloud.githubusercontent.com/assets/17522547/14015415/b60db4c4-f1f3-11e5-9bfd-3b743ef5c971.jpg)

**Comment by MxCen** [comment]
This should be the complete update package 9.2.0-20J

Not 9.1.0

![full title](https://cloud.githubusercontent.com/assets/17522547/14015464/2abd310a-f1f4-11e5-8ab5-f93231a4077a.png)

**Comment by Plailect** [comment]
Your downgrade pack is outdated, use the one [here](https://github.com/Plailect/Guide/wiki/Part-2-(Downgrading)).
