### ISSUE TITLE
Region Free Launcher appearing when trying to access PlaiSysUpdater?

### ISSUE THREAD

**Issue by LonLonSurprise** [Plailect/PlaiSysUpdater#16]
In Part 2 of the guide, boot homebrew launcher, tap PlaiSysUpdater and all I see is the Region Free Launcher for some reason. Redid everything with same results. Using a 10.7.0-32U old 3DS. I attached a photo for reference. Any Ideas? Other people are having this issue as well.
![problem](https://cloud.githubusercontent.com/assets/21012547/17645092/a55d9d6a-6160-11e6-921d-0b602632051d.jpg)

**Comment by Plailect** [comment]
Download again, I updated the release archive.
