### ISSUE TITLE
PlaiSysUpdater am:u access issue

### ISSUE THREAD

**Issue by Kazakian** [Plailect/PlaiSysUpdater#17]
Hi. The newest PlaiSysUpdater, version five, has been giving me some issues. I launch the updater, press Y, and it loads up correctly, but it says:

Checking for am:u...
Did not get am:u handle!
Attempting svchax...
Initted svchax...
Initted apt...
Checking for am:u...
FAIL
Can't get am:u service ... try again :x 
press (A) to exit...

I have tried almost anything I would know to fix this but just can't seem to downgrade. I am downgrading to 9.2.0 and I am on an Old 3DS with version 11.0.0-33U. Any fix?

**Comment by Plailect** [comment]
You cannot downgrade to 11.0.0 without a [firmware downgrade](https://github.com/Plailect/Guide/wiki/Firmware-Downgrade).
