### ISSUE TITLE
PlaiSysUpdater am:u access issue

### ISSUE THREAD

**Issue by Chrs2021** [Plailect/PlaiSysUpdater#18]
I am having the same issue with this. I have 2ds with 11.0.0-33U with downgraded firmware via DSiware downgrade method, dgtool returned 0 0 after writing. i am getting this

Checking for am:u...
Did not get am:u handle!
Attempting svchax...
Initted svchax...
Initted apt...
Checking for am:u...
FAIL
Can't get am:u service ... try again :x 
press (A) to exit...

I have been using OOThax, browserhax and menuhaxx as entry points. to test if my native firm was downgraded i injected the OOThax 10-4-0 Payload in my cartridge this ran fine. i would give you more stuff but i don't really know how to debug something like this.

**Comment by mariogamer2** [comment]
You must firmware downgrade first.

**Comment by Chrs2021** [comment]
didn't I explain that I did that? "11.0.0-33U with downgraded firmware via DSiware downgrade method, dgtool returned 0 0 after writing"

**Comment by mariogamer2** [comment]
Ah sorry. I must see the page for dsiware,so...

**Comment by KonsoleHL** [comment]
same here.

New3DS XL (E) was on 11.0 Hardmod done all went fine but...

______________________________________________
Checking for am:u...       
Did not get am:u handle!       
Attempting svchax...       
Innitted svchax...       
Checking for am:u...       
FAIL       
Can´t get am:u service ..... try again :x       
press (A) to exit... 
_______________________________________________

After that Black Screen .
