### ISSUE TITLE
Can't get am:u service...

### ISSUE THREAD

**Issue by Collasox** [Plailect/PlaiSysUpdater#19]
Hi, I tried like 200 times to downgrade a New 3DS with DSI Ware Downgrade and i get this error code, i've tried formatting, with ftbrony, with Safe SysUpdater and SysUpdater, and never work. I've tried so many times, what can I do? My 3ds is in 10.3 but shows 11.0.

**Comment by Plailect** [comment]
Use [3DSident](https://github.com/joel16/3DSident/releases/latest), then reply with the kernel version and firmware version

**Comment by Collasox** [comment]
Uuuuups, it's 10.4, not 10.3.
Kernel: 2.51-0

**Comment by fincs** [comment]
https://3dbrew.org/wiki/FIRM#NATIVE_FIRM

That is 11.0 FIRM.

**Comment by Collasox** [comment]
That means the DSI Downgrade failed?

**Comment by Plailect** [comment]
Correct, you did something wrong.

**Comment by Collasox** [comment]
Thanks, i'm going to repeat all the process XD
