### ISSUE TITLE
Did not get am:u handle! (Firmware (9.4))

### ISSUE THREAD

**Issue by knguyen9095** [Plailect/PlaiSysUpdater#20]
Checking for am:u...
Did not get am:u handle!
Attempting svchax...

I am having this trouble downgrading from  9.4 to 9.2
I always end up this error. /: I did this countless time even with the ftpbrony too.
BTW. This is an old 3ds.

Edited: I think I know the problem. The browser server is down

**Comment by Plailect** [comment]
That's completely unrelated; this is an svchax issue.
