### ISSUE TITLE
"Black Screen of Death" after it's done verifying the CIAs

### ISSUE THREAD

**Issue by JershXL** [Plailect/PlaiSysUpdater#4]
n3DS XL on 10.7 w/ latest PlaiSysUpdater (Yes, I am following your guide)

**Comment by Plailect** [comment]
Try again, I cannot reproduce on my 10.7 n3ds w/ latest PlaiSysUpdater

**Comment by JershXL** [comment]
Apparently Nautilus has issues copying files correctly, because I decided to recopy the update folder to the microSD from the terminal and now it's working...
