### ISSUE TITLE
Repeatadly Stuck at "HAX INIT..."

### ISSUE THREAD

**Issue by aaronson2012** [Plailect/PlaiSysUpdater#6]
Hello I am trying to downgrade my New 3DS to 9.2 from 10.7. I keep running into an issue. I can always see the button prompts when I start PlaiSysUpdater but then when I press Y to start the downgrade to 9.2 it always gets stuck at "HAX INIT...". I have tried at least 10 times now.

My entry method is smashbroshax if that matters.

Any advice? Thanks.

**Comment by aaronson2012** [comment]
I'm using this guide by the way: https://github.com/Plailect/Guide/wiki/Part-2-%28Downgrading%29

**Comment by aaronson2012** [comment]
It seems smashbroshax was the issue. I got it working with oothax.

**Comment by chinhodado** [comment]
I have the same problem, using smashhax on N3DS XL 10.7.0-32U and smash 1.0.0. Always stuck at HAX INIT... Tried going to menuhax_manager then quit to HBL before downgrading, didn't work either.

**Comment by rubin55** [comment]
I have the same issue; 10.7.0 32 E with smashborshax, always hang at HAXINIT. Very disappointing because I don't have Ocarina of Time :-/

**Comment by Threshold0** [comment]
I don't expect any update on this issue, but for future reference, menuhax also gets stuck.

**Comment by Plailect** [comment]
Tell @aliaspider to fix svchax

**Comment by thejsa** [comment]
Same w/ NH2 or Menuhax, 9.7.0-E 2DS.
