### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by Flat** [Plailect/PlaiSysUpdater#7]
CMake fails to configure the build.
>cmake version 3.5.1

>cmake .. -DCMAKE_TOOLCHAIN_FILE=../DevkitArm3DS.cmake
>...
>CMake Error at CMakeLists.txt:23 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.

**Comment by Plailect** [comment]
This happens if you do not so git clone --recursive to grab the submodules aswell.

**Comment by Flat** [comment]
I see, my apologies I didn't notice the submodules.
